
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar";
import { GlobalContext, GlobalContextProvider } from "@/Contexts/Context";
import { useContext } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Navbar />
          <div>
            <Sidebar />
            {children}
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
